theme: jekyll-theme-cayman
lang: "es-ES"
logo: "https://repository-images.githubusercontent.com/265373411/8dfdbe00-9abb-11ea-9563-ce928d0d57a1"
title: "Covid Cuba"
description: "Aplicación gratuita desarrollada con el fin de proporcionar información actualizada en la lucha contra el COVID-19 a usuarios residentes en Cuba"
